formatter: markdown table

version: ">= 0.17.0"

sections:
  hide: []
  show: []

content: |-
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  anchor: true
  escape: true
  indent: 2
  required: true
  sensitive: true
  type: true
